update

diff --git a/.github/workflows/validate-submission.yml b/.github/workflows/validate-submission.yml
--- a/.github/workflows/validate-submission.yml
+++ b/.github/workflows/validate-submission.yml
@@ -20,6 +20,14 @@ jobs:
             
             echo "--- cheching folder: $FOLDER_NAME ---"
 
+            PR_AUTHOR="${{ github.event.pull_request.user.login }}"
+            EXISTING_AUTHOR=$(git show origin/main:pages/$FOLDER_NAME/config.json | jq -r '.github_username')
+
+            if [ "$EXISTING_AUTHOR" != "null" ] && [ "$EXISTING_AUTHOR" != "$PR_AUTHOR" ]; then
+              echo "::error::Access Denied! Only $EXISTING_AUTHOR can modify the folder $FOLDER_NAME."
+              exit 1
+            fi
+
             if [ ! -f "$CONFIG_PATH" ]; then
               echo "::error file=$CONFIG_PATH::config.json file is missing"
               exit 1
